
all:
	$(MAKE) -C parser_regex2auto
	$(MAKE) -C parser_file2auto
	$(MAKE) -C reconnaissance

clean:
	$(MAKE) -C hybride_automata clean
	$(MAKE) -C parser_file2auto clean
	$(MAKE) -C parser_regex2auto clean
	$(MAKE) -C reconnaissance clean
	$(MAKE) -C test clean
